<?php

namespace Bricks\Custom\Twentysteps\AlexaBrick\AlexaBundle\Entity;

use Bricks\AbstractCustomBundle\Entity\AbstractUserRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends AbstractUserRepository {

    public function getFilterFieldNames() {
        return ['firstName','lastName','username'];
    }

}
