<?php

namespace Bricks\Custom\Twentysteps\AlexaBrick\AlexaBundle\Controller;

use Bricks\Infrastructure\CoreBrick\CoreBundle\Controller\AbstractBricksController;
use Symfony\Component\HttpFoundation\Request;

class AbstractAuthenticatedController extends AbstractBricksController {
	

	public function setupController(Request $request) {
		$request->request->set('projectId','alexa');
		parent::setupController($request); // TODO: Change the autogenerated stub
	}
	
}