# show Wordpress pages and posts

bricks.custom.twentysteps_alexa.content.page:
    path: /{_locale}/c/{slug}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:Content:page, project: alexa }
    methods: [GET]

bricks.custom.twentysteps_alexa.content.post:
    path: /{_locale}/b/{slug}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:Content:post, project: alexa }
    methods: [GET]


