bricks.custom.twentysteps_alexa.api.authenticated.token.create:
    path: /token/create.{_format}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:AuthenticatedAPIUser:createToken, _format: json, project: alexa }
    methods: [POST]

bricks.custom.twentysteps_alexa.api.authenticated.user.self.profile.update:
    path: /users/self/profile/update.{_format}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:AuthenticatedAPIUser:updateProfile, _format: json, project: alexa }
    methods: [POST]

bricks.custom.twentysteps_alexa.api.authenticated.device.info:
    path: /device/info.{_format}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:AuthenticatedAPIUser:updateDeviceInfo, _format: json, project: alexa }
    methods: [PUT]

bricks.custom.twentysteps_alexa.api.authenticated.device.info.get:
    path: /device/info/update.{_format}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:AuthenticatedAPIUser:updateDeviceInfoGet, _format: json, project: alexa }
    methods: [GET]

bricks.custom.twentysteps_alexa.api.authenticated.user.self.info:
    path: /users/self/info.{_format}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:AuthenticatedAPIUser:info, _format: json, project: alexa }
    methods: [GET]

bricks.custom.twentysteps_alexa.api.authenticated.user.self.password:
    path: /users/self/password.{_format}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:AuthenticatedAPIUser:changePassword, _format: json, project: alexa }
    methods: [GET]

bricks.custom.twentysteps_alexa.api.authenticated.user.self.username:
    path: /users/self/username.{_format}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:AuthenticatedAPIUser:changeUsername, _format: json, project: alexa }
    methods: [GET]

bricks.custom.twentysteps_alexa.api.authenticated.user.self.firstName:
    path: /users/self/firstName.{_format}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:AuthenticatedAPIUser:changeFirstName, _format: json, project: alexa }
    methods: [GET]

bricks.custom.twentysteps_alexa.api.authenticated.user.self.lastName:
    path: /users/self/lastName.{_format}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:AuthenticatedAPIUser:changeLastName, _format: json, project: alexa }
    methods: [GET]

bricks.custom.twentysteps_alexa.api.authenticated.user.self.updateNamesAndCredentitals:
    path: /users/self/namesAndCredentials/update.{_format}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:AuthenticatedAPIUser:updateNamesAndCredentials, _format: json, project: alexa }
    methods: [GET]

bricks.custom.twentysteps_alexa.api.authenticated.user.self.settings.update:
    path: /users/self/settings/update.{_format}
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:AuthenticatedAPIUser:updateSetting, _format: json, project: alexa }
    methods: [GET]