# Custom

bricks.custom.twentysteps_alexa.api.alexa:
    resource: "@BricksCustomTwentystepsAlexaBundle/Resources/config/routing.api.1.0.alexa.yml"
    host: "%bricks_api_host%"
    prefix: "/bricks/api/v1.0/alexa/alexa"
    defaults: { _format: "json" }
    requirements:
        bricks_api_host: "%bricks_api_host%"


# REST Generic

bricks.custom.twentysteps_alexa.rest:
    resource: '@BricksCustomTwentystepsAlexaBundle/Action/'
    prefix: "%bricks_api_rest_prefix%"
    type:     'annotation'
