# Custom

bricks.custom.twentysteps_alexa.api.alexa:
    resource: "@BricksCustomTwentystepsAlexaBundle/Resources/config/routing.api.1.0.alexa.yml"
    host: "%bricks_api_host%"
    prefix: "/bricks/api/v1.0/alexa/alexa"
    defaults: { _format: "json" }
    requirements:
        bricks_api_host: "%bricks_api_host%"


# Generic user management

bricks.custom.twentysteps_alexa.api.authenticated:
    resource: "@BricksCustomTwentystepsAlexaBundle/Resources/config/routing.api.1.0.authenticated.yml"
    prefix: "/bricks/api/v1.0/alexa/authenticated"
    host: "%bricks_api_host%"
    defaults: { _format: "json" }
    requirements:
        bricks_api_host: "%bricks_api_host%"


bricks.custom.twentysteps_alexa.api.signin:
    resource: "@BricksCustomTwentystepsAlexaBundle/Resources/config/routing.api.1.0.signin.yml"
    prefix: "/bricks/api/v1.0/alexa"
    host: "%bricks_api_host%"
    defaults: { _format: "json" }
    requirements:
        bricks_api_host: "%bricks_api_host%"


# Generic REST

bricks.custom.twentysteps_alexa.rest:
    resource: '@BricksCustomTwentystepsAlexaBundle/Action/'
    prefix: "%bricks_api_rest_prefix%"
    type:     'annotation'

# OAuth2

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"