# regular login

bricks.custom.twentysteps_alexa.user.register:
    path: /{_locale}/register
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:register, project: alexa }
    methods: [GET,POST]

bricks.custom.twentysteps_alexa.user.confirm:
    path: /{_locale}/confirm
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:confirm, project: alexa }
    methods: [GET]

bricks.custom.twentysteps_alexa.user.resend_activation_link:
    path: /{_locale}/resend-activation-link
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:resendActivationLink, project: alexa }
    methods: [GET,POST]

bricks.custom.twentysteps_alexa.user.login:
    path: /{_locale}/login
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:login, project: alexa }
    methods: [GET]

bricks.custom.twentysteps_alexa.user.check:
    path:   /{_locale}/authenticated/check

bricks.custom.twentysteps_alexa.user.home:
    path:   /{_locale}/authenticated/home
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:home, project: alexa}

bricks.custom.twentysteps_alexa.user.logout:
    path:   /{_locale}/authenticated/logout

bricks.custom.twentysteps_alexa.user.reset_password:
    path:   /{_locale}/reset-password
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:resetPassword, project: alexa}
    methods: [GET,POST]


# alexa account linking login

bricks.custom.twentysteps_alexa.user.alexa.register:
    path: /oauth/v2/register
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:registerAlexa, project: alexa, _locale: de }
    methods: [GET,POST]

bricks.custom.twentysteps_alexa.user.alexa.confirm:
    path: /{_locale}/alexa/confirm
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:confirmAlexa, project: alexa }
    methods: [GET]

bricks.custom.twentysteps_alexa.user.alexa.resend_activation_link:
    path: /{_locale}/alexa/resend-activation-link
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:resendActivationLinkAlexa, project: alexa }
    methods: [GET,POST]

bricks.custom.twentysteps_alexa.user.alexa.login:
    path: /oauth/v2/login
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:loginAlexa, project: alexa, _locale: de }
    methods: [GET]

bricks.custom.twentysteps_alexa.user.alexa.check:
    path:   /oauth/v2/authenticated/check

bricks.custom.twentysteps_alexa.user.alexa.pre_authorize:
    path:   /oauth/v2/authenticated/pre-authorize
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:preAuthorizeAlexa, project: alexa, _locale: de }
    methods: [GET]

fos_oauth_server_authorize:
    path: /oauth/v2/authenticated/authorize
    defaults: { _controller: FOSOAuthServerBundle:Authorize:authorize, _locale: de }
    methods: [GET,POST]

fos_oauth_server_token:
    path: /oauth/v2/authenticated/token
    defaults: { _controller: fos_oauth_server.controller.token:tokenAction, _locale: de }
    methods: [GET,POST]

fos_oauth_server_profile_show:
    path:   /oauth/v2/authenticated/home
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:homeAlexa, project: alexa, _locale: de}

bricks.custom.twentysteps_alexa.user.alexa.logout:
    path:   /oauth/v2/authenticated/logout

bricks.custom.twentysteps_alexa.user.alexa.reset_password:
    path:   /{_locale}/alexa/reset-password
    defaults: { _controller: BricksCustomTwentystepsAlexaBundle:User:resetPasswordAlexa, project: alexa}
    methods: [GET,POST]

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /{_locale}/authenticated/connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /{_locale}/authenticated/connect

hwi_oauth_check_google:
    path: /{_locale}/authenticated/connect/check/google
