# Custom user management (Web)

bricks.custom.twentysteps_alexa.user:
    resource: "@BricksCustomTwentystepsAlexaBundle/Resources/config/routing.user.yml"
    host: "%bricks_custom_twentysteps_alexa_host%"
    prefix: "/"
    requirements:
        bricks_custom_twentysteps_alexa_host: "%bricks_custom_twentysteps_alexa_host%"

# Custom API

bricks.custom.twentysteps_alexa.api.alexa:
    resource: "@BricksCustomTwentystepsAlexaBundle/Resources/config/routing.api.1.0.alexa.yml"
    host: "%bricks_api_host%"
    prefix: "/bricks/api/v1.0/alexa/alexa"
    defaults: { _format: "json" }
    requirements:
        bricks_api_host: "%bricks_api_host%"

bricks.custom.twentysteps_alexa.api.api_ai:
    resource: "@BricksCustomTwentystepsAlexaBundle/Resources/config/routing.api.1.0.api_ai.yml"
    host: "%bricks_api_host%"
    prefix: "/bricks/api/v1.0/alexa/api-ai"
    defaults: { _format: "json" }
    requirements:
        bricks_api_host: "%bricks_api_host%"

# Wordpress CMS (Web)

bricks.custom.twentysteps_alexa.content:
    resource: "@BricksCustomTwentystepsAlexaBundle/Resources/config/routing.content.yml"
    host: "%bricks_custom_twentysteps_alexa_host%"
    prefix: "/"
    requirements:
        bricks_custom_twentysteps_alexa_host: "%bricks_custom_twentysteps_alexa_host%"

# Generic REST

bricks.custom.twentysteps_alexa.rest:
    resource: '@BricksCustomTwentystepsAlexaBundle/Action/'
    prefix: "%bricks_api_rest_prefix%"
    type:     'annotation'

