imports:
    - { resource: "../../vendor/20steps/bricks/src/Bricks/Platform/etc/config/config_test_clean.yml" }
    - { resource: config.yml }
    - { resource: orm_test_clean.yml }
    - { resource: framework_test.yml }
    - { resource: logging_test.yml }
    - { resource: profiler_test.yml }
    - { resource: mail_test.yml }
    - { resource: fixtures_test.yml }
    - { resource: monitoring_test.yml }



